/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2022-09-22 20:02:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ConsultarBienPorOrdendeCompra_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1663876895275L));
    _jspx_dependants.put("jar:file:/C:/Users/Carlo/OneDrive/Escritorio/Aplicacion_Web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/lp2_2022_Proyecto/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1652387232000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	if(request.getSession().getAttribute("LISTA")==null)
		response.sendRedirect("login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Consultar Bien por Codigo de Compra</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Bootstrap CSS -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css\" rel=\"stylesheet\">´\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/stylePages.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tbackground-image:url(\"https://quiasma.com.mx/wp-content/uploads/2017/03/fondo-blanco.jpg\");\r\n");
      out.write("\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\tbackground-attachment: fixed;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bg{\r\n");
      out.write("\t\tbackground-position:center center;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.modal-header{\r\n");
      out.write("\t\tcolor:#fff;\r\n");
      out.write("\t\tbackground: black;\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("  \t\tjustify-content: center;  \t\t\r\n");
      out.write("  \t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.help-block {\r\n");
      out.write("\t  \t\tcolor: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-group.has-error .form-control-label {\r\n");
      out.write("\t  color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-group.has-error .form-control {\r\n");
      out.write("\t  border: 1px solid red;\r\n");
      out.write("\t  box-shadow: 0 0 0 0.2rem rgba(250, 16, 0, 0.18);\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "partialMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- Añadir class .home  -->\r\n");
      out.write("\t<div class=\"container home\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fremove_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<h2 class=\"text-center mt-5\">Consultar Bien por Codigo de Compra</h2>\r\n");
      out.write("\t\t<form>\r\n");
      out.write("\t\t   <div class=\"form-row mt-5\">\r\n");
      out.write("\t\t\t    <div class=\"col-auto\">\r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t   <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t    <select class=\"form-control\" name=\"condicion\" id=\"idCompra\">\r\n");
      out.write("\t\t\t\t      <option value=\" \">[Seleccione Codigo Compra]</option>\r\n");
      out.write("\t\t\t\t    </select>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    <div class=\"col-auto mt-2\">\r\n");
      out.write("\t\t\t      <button type=\"button\" class=\"btn btn-success mb-2\" id=\"btn-consultar\">Consultar</button>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"mt-4\">\r\n");
      out.write("\t\t\t<table id=\"tableConsultar\" class=\"table table-striped table-bordered\" style=\"width:100%\">\r\n");
      out.write("\t\t        <thead>\r\n");
      out.write("\t\t            <tr>\r\n");
      out.write("\t\t               <th>CÓDIGO DEL BIEN</th>\r\n");
      out.write("\t\t                <th>DESCRIPCIÓN</th>\r\n");
      out.write("\t\t                <th>CANTIDAD</th>\r\n");
      out.write("\t\t                <th>PROVEEDOR</th>\r\n");
      out.write("\t\t                <th>FECHA LLEGADA</th>\r\n");
      out.write("\t\t                 <th>CODIGO COMPRA</th>\r\n");
      out.write("\t\t                <th></th>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t        </thead>\r\n");
      out.write("\t\t        <tbody>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- FIN - Modal PARA EDITAR-->\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//\r\n");
      out.write("\t\tllenarTabla();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\",\"#btn-consultar\",function(){\r\n");
      out.write("\t\t\tlet cod;\r\n");
      out.write("\t\t\tcod=$(\"#idCompraBuscar\").val();\r\n");
      out.write("\t\t\t$(\"#tableConsultar tbody\").empty();\r\n");
      out.write("\t\t\t$.get(\"ServletBienporCompraJSON?cod=\"+cod,function(response){\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableConsultar\").append(\"<tr><td>\"+item.codigo_bien+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.descrip_bien+\"</td><td>\"+item.cantidad_bien+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.nom_provee+\"</td><td>\"+item.fecha_llegada+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.codigoOrdendeCompra+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<button type='button' class='btn btn-success btn-datos' data-bs-toggle='modal'\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"data-bs-target='#BienModal'>Editar</button></td></tr>\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\",\"#btn-consultar\",function(){\r\n");
      out.write("\t\t\tlet cod;\r\n");
      out.write("\t\t\tcod=$(\"#idCompra\").val();\r\n");
      out.write("\t\t\t$(\"#tableConsultar tbody\").empty();\r\n");
      out.write("\t\t\t$.get(\"ServletBienporCompraJSON?cod=\"+cod,function(response){\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableConsultar\").append(\"<tr><td>\"+item.codigo_bien+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.descrip_bien+\"</td><td>\"+item.cantidad_bien+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.nom_provee+\"</td><td>\"+item.fecha_llegada+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.codigoOrdendeCompra+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<button type='button' class='btn btn-success btn-datos' data-bs-toggle='modal'\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"data-bs-target='#BienModal'>Editar</button></td></tr>\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t}) \t\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction llenarTabla(){\r\n");
      out.write("\t\t\t$.get(\"ServletGuiaListaJSON\",function(response){\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#idCompra\").append(\"<option>\"+item.codigoguiacompra+\"</option>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-datos\",function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tlet cod,descrip,cant,nomprovee,fechallegada,codigocompra;\r\n");
      out.write("\t\t\tcod=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\tdescrip=$(this).parents(\"tr\").find(\"td\")[1].innerHTML;\r\n");
      out.write("\t\t\tcant=$(this).parents(\"tr\").find(\"td\")[2].innerHTML;\r\n");
      out.write("\t\t\tnomprovee=$(this).parents(\"tr\").find(\"td\")[3].innerHTML;\r\n");
      out.write("\t\t\tfechallegada=$(this).parents(\"tr\").find(\"td\")[4].innerHTML;\r\n");
      out.write("\t\t\tcodigocompra=$(this).parents(\"tr\").find(\"td\")[5].innerHTML;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t//console.log(response);\r\n");
      out.write("\t\t\t\t//asignar a los controles las claves del parámetro response\r\n");
      out.write("\t\t\t\t$(\"#idCodigo\").val(cod);\r\n");
      out.write("\t\t\t\t$(\"#idDescripcion\").val(descrip);\r\n");
      out.write("\t\t\t\t$(\"#idCantidad\").val(cant);\r\n");
      out.write("\t\t\t\t$(\"#idNombreproveedor\").val(nomprovee);\r\n");
      out.write("\t\t\t\t$(\"#idFechallegada\").val(fechallegada);\r\n");
      out.write("\t\t\t\t$(\"#idCompra\").val(codigocompra);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /ConsultarBienPorOrdendeCompra.jsp(52,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
          out.write("\t\t\t\t  <strong>MENSAJE : </strong> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" \r\n");
          out.write("\t\t\t\t  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent(null);
      // /ConsultarBienPorOrdendeCompra.jsp(58,3) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("param.MENSAJE");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }
}
